spring:
  application:
    name: medium-obo-flow-api-a
  security:
    oauth2:
      resource-server:
        jwt:
          audiences: ${OBO_API_A_CLIENT_ID}
          issuer-uri: https://sts.windows.net/<tenant-id>/